import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import useKeyEvent from "use-key-event";
import { useState } from "react";

export default function Home() {
  const [width, setWidth] = useState(1);
  const handleEnterPress = () => {
    setTimeout(() => {
      setWidth(width + 1);
    }, 100);
    console.log(width);
  };

  useKeyEvent("Enter", handleEnterPress);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        style={{
          backgroundColor: "blue",
          padding: "2rem",
          width: `${width.toString()}rem`,
          height: `${width.toString()}rem`,
          borderRadius: "50%",
          transition: "ease-in",
        }}
      ></div>
    </div>
  );
}
