import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div style={{ display: "flex" }}>
        <div style={{ textAlign: "center", width: "100%" }}>
          <div
            style={{
              width: "100%",
              height: "90vh",
              backgroundColor: "red",
              borderRadius: "4rem",
            }}
          >
            The best
          </div>
        </div>
        <div>The best</div>
      </div>
    </div>
  );
}
